### PR TITLE
Fix #491 segfault in RdKafka\TopicPartition::__construct()

### LINKED ISSUE #491: [6.0.0RC1] segfault in test suite
```
TEST 32/32 [tests/topic_partition.phpt]
========DIFF========
001+ Termsig=11
001- object(RdKafka\TopicPartition)#1 (4) {
002-   ["topic"]=>
003-   string(4) "test"
004-   ["partition"]=>
005-   int(-1)
006-   ["offset"]=>
007-   int(42)
008-   ["err"]=>
009-   int(0)
010- }
011- array(3) {
012-   ["topic"]=>
013-   string(4) "test"
014-   ["partition"]=>
015-   int(-1)
016-   ["offset"]=>
017-   int(42)
018- }
019- object(RdKafka\TopicPartition)#1 (4) {
020-   ["topic"]=>
021-   string(3) "foo"
022-   ["partition"]=>
023-   int(123)
024-   ["offset"]=>
025-   int(43)
026-   ["err"]=>
027-   int(0)
028- }
========DONE========
FAIL RdKafka\TopicPartition [tests/topic_partition.phpt] 

```

### PR DESCRIPTION
**Pull request by remicollet**
Drop nullable attribute, default value should be enough.

If you want to keep it, you need an additional arg to store null, and test it (probably don't worth it)
```

    if (zend_parse_parameters(ZEND_NUM_ARGS(), "sl|l!", &topic, &topic_len, &partition, &offset, &is_null) == FAILURE) {
        ...
    }
    if (is_null) {
    ....
    }
```

### CODE REVIEW

**Comment by andypost** [comment]
@remicollet Thank you a lot! it passed all arches https://gitlab.alpinelinux.org/alpine/aports/-/pipelines/100300

**Comment by arnaud-lb** [comment]
Thanks @remicollet  !

**Comment by andypost** [comment]
please create RC2 release

**Comment by arnaud-lb** [comment]
I will release it later today :)

**Comment by arnaud-lb** [comment]
https://pecl.php.net/package/rdkafka/6.0.0RC2

**Comment by andypost** [comment]
Thank you!

**Pull request merged**
