### PR TITLE
expose flush

### PR DESCRIPTION
**Pull request by nick-zh**
@arnaud-lb i removed the poll in the destructor, because of issue https://github.com/arnaud-lb/php-rdkafka/issues/196, where the problem is, that when the broker is not available, the poll hangs forever in the destructor (because unlike for flush, there is no timeout). With flush and purge exposed, this gives the user enough flexibility to handle this on it's own i think.
Let me know what you think

Relates to: https://github.com/arnaud-lb/php-rdkafka/pull/144

### CODE REVIEW

**Comment by arnaud-lb** [comment]
I we remove `poll()` in destruct, we don't guarantee that messages are sent anymore. what do you think about https://github.com/arnaud-lb/php-rdkafka/issues/196#issuecomment-523858096 ?

**Comment by nick-zh** [comment]
@arnaud-lb i think we can remove poll in destruct, i updated the readme and doc examples accordingly

**Comment by arnaud-lb** [comment]
Thanks !

**Comment by anam-hossain** [comment]
@nick-zh An example would be great. Thanks for the PR. We needed this.

**Comment by nick-zh** [comment]
@anam-hossain no worries, there is a very small example here: https://arnaud.le-blanc.net/php-rdkafka/phpdoc/rdkafka.examples-producer.html and also in the readme: https://github.com/arnaud-lb/php-rdkafka#proper-shutdown
Let me know if something is unclear or if i can improve the docs

**Comment by anam-hossain** [comment]
@nick-zh Thanks. The docs look good. However, for the beginner, it is difficult to understand when to use purge and flush. Furthermore, how to handle the failure. A complete example will help us a lot.

**Comment by nick-zh** [comment]
@anam-hossain thank you for the feedback, i added some more info to the doc, until that is merged, i think a good example would probably look a little bit like this:
```
$conf = new RdKafka\Conf();
$conf->set('metadata.broker.list', 'localhost:9092');

//If you need to produce exactly once and want to keep the original produce order, uncomment the line below
//$conf->set('enable.idempotence', 'true');

$producer = new RdKafka\Producer($conf);

$topic = $producer->newTopic("test");

for ($i = 0; $i < 10; $i++) {
    $topic->produce(RD_KAFKA_PARTITION_UA, 0, "Message $i");
    $producer->poll(0);
}

for ($flushRetries = 0; $flushRetries < 10; $flushRetries++) {
    $result = $producer->flush(10000);
    if (RD_KAFKA_RESP_ERR_NO_ERROR === $result) {
        break;
    }
}

if (RD_KAFKA_RESP_ERR_NO_ERROR !== $result) {
    throw new \RuntimeException('Was unable to flush, messages might be lost!');
}
```
I think most people won't make use of `purge`. When you use `produce`, messages land in an internal queue before being sent to Kafka. With `purge` you can empty that internal queue (or even kill inflight messages). I think most people want their messages sent once they used `produce`.
Let me know if you need more clarification on something.

**Comment by Steveb-p** [comment]
@nick-zh I'm pretty certain `flush` does not need to be in a loop. At least I'm wondering if it has to :thinking: 

https://docs.confluent.io/3.1.1/clients/librdkafka/rdkafka_8h.html#aaff06c4372bce917c17f3c1a5d8b205d

**Comment by nick-zh** [comment]
@Steveb-p the problem is, flush can return `RD_KAFKA_RESP_ERR__TIMED_OUT` if it wasn't successful, to be on the safe side, you would want to retry that (it mostly won't happen i hope).
Of course you could also just do:
```
$result = $producer->flush(10000);

if (RD_KAFKA_RESP_ERR_NO_ERROR !== $result) {
    throw new \RuntimeException('Was unable to flush, messages might be lost!');
}
```

**Comment by anam-hossain** [comment]
@nick-zh Thank you very much. Much appreciated.

**Pull request merged**
