### PR TITLE
fix windows build

### LINKED ISSUE #440: v5.0.0 PECL build fails on Windows
* PHP version:  8.0.1
 * librdkafka version:  1.5.3
 * php-rdkafka version:   5.0.0
 * kafka version:

PECL build fails for latest v5.0.0 DLL build.
See logs at  https://windows.php.net/downloads/pecl/releases/rdkafka/5.0.0/logs/php_rdkafka-5.0.0-8.0-nts-vs16-x64-logs.zip

```shell
ext\rdkafka\kafka_consumer.c(789): warning C4133: 'function': incompatible types - from 'long *' to 'int64_t *'
ext\rdkafka\kafka_consumer.c(789): warning C4133: 'function': incompatible types - from 'long *' to 'int64_t *'
metadata_topic.c
queue.c
rdkafka.c
topic.c
topic_partition.c
ext\rdkafka\rdkafka.c(639): warning C4133: 'function': incompatible types - from 'long *' to 'int64_t *'
ext\rdkafka\rdkafka.c(639): warning C4133: 'function': incompatible types - from 'long *' to 'int64_t *'
	rc /nologo  /I . /I main /I Zend /I TSRM /I ext /n /fo C:\php-snap-build\obj\8.0-nts-windows-vs16-x64\Release\php_rdkafka.dll.res /d FILE_DESCRIPTION="\"rdkafka\"" /d FILE_NAME="\"php_rdkafka.dll\"" /d URL="\"http://www.php.net\"" /d INTERNAL_NAME="\"RDKAFKA extension\"" /d THANKS_GUYS="\"Thanks to Arnaud Le Blanc\"" win32\build\template.rc
	"link.exe" @"C:\php-snap-build\obj\8.0-nts-windows-vs16-x64\Release\resp\RDKAFKA_GLOBAL_OBJS.txt" C:\php-snap-build\obj\8.0-nts-windows-vs16-x64\Release\php8.lib librdkafka.lib kernel32.lib ole32.lib user32.lib advapi32.lib shell32.lib ws2_32.lib Dnsapi.lib psapi.lib bcrypt.lib argon2_a.lib C:\php-snap-build\obj\8.0-nts-windows-vs16-x64\Release\php_rdkafka.dll.res /out:C:\php-snap-build\obj\8.0-nts-windows-vs16-x64\Release\php_rdkafka.dll /dll /nologo /GUARD:CF /incremental:no /debug /opt:ref,icf /libpath:"C:\php-snap-build\php-src\php80\x64\deps\lib" /libpath:"C:\php-snap-build\dep-aux\vs16\x64\librdkafka\lib" /NXCOMPAT /DYNAMICBASE /libpath:"..\deps\lib" 
   Creating library C:\php-snap-build\obj\8.0-nts-windows-vs16-x64\Release\php_rdkafka.lib and object C:\php-snap-build\obj\8.0-nts-windows-vs16-x64\Release\php_rdkafka.exp
rdkafka.obj : error LNK2019: unresolved external symbol create_kafka_error referenced in function kafka_log_syslog_print
rdkafka.obj : error LNK2019: unresolved external symbol kafka_error_minit referenced in function register_err_constants
C:\php-snap-build\obj\8.0-nts-windows-vs16-x64\Release\php_rdkafka.dll : fatal error LNK1120: 2 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\link.exe"' : return code '0x460'
Stop.
```

I've replicated the error locally with librdkafka v1.5.3, v1.4.4 , v1.3.0, v0.11.6 .

### PR DESCRIPTION
**Pull request by nick-zh**
@arnaud-lb this should fix the windows build (#440), fix was reported by @cmb69 
Would be cool if you could merge and release this soon

### CODE REVIEW

**Comment by arnaud-lb** [comment]
Thanks @nick-zh

**Comment by aand18** [comment]
Hello, 
any way of getting this to build on PECL site? 
Would a 5.0.1 release suffice, or there are other issues on PECL's side?

**Comment by cmb69** [comment]
I think a new release should suffice.

**Comment by scaytrase** [comment]
Where can we find DLL for php8? https://pecl.php.net/package/rdkafka was not updated for more than half a year

**Comment by pulzarraider** [comment]
@arnaud-lb can you please create new tag 5.0.1 (or 5.1.0) so this fix will be part of the release?

**Pull request merged**
