### PR TITLE
fix segfault on Producer::newQueue

### PR DESCRIPTION
**Pull request by nick-zh**
https://github.com/arnaud-lb/php-rdkafka/issues/272

### CODE REVIEW

**Comment by nick-zh** [comment]
@arnaud-lb let me know if this is ok, first i wanted to initialize queue always, but since it seems this feature is only thought for consumers, i decided to return a `RD_KAFKA_RESP_ERR__NOT_IMPLEMENTED` instead, since `newQueue` is not meant for producers. Let me know what you think.

**Comment by arnaud-lb** [comment]
Could we remove the method from `RdKafka\Kafka`, and only add it on `RdKafka\Consumer` ? Otherwise, we should throw an exception (returning a non-`RdKafka\Queue` might be confusing / unexpected).

**Comment by nick-zh** [comment]
@arnaud-lb totally, i missed the consumer and producer blocks, but this of course makes way more sense actually :+1:

**Comment by arnaud-lb** [comment]
Thanks !

**Pull request merged**
