### PR TITLE
Add PHP 7.3 and librdkafka 1.0.x into build matrix

### PR DESCRIPTION
**Pull request by renatomefi**

### CODE REVIEW

**Comment by nick-zh** [comment]
@renatomefi would probably make sense to add librdkafka 1.1.x as well

**Comment by renatomefi** [comment]
Hey @nick-zh, 1.1 branch isn't available yet since it's master, they'll probably add it when 1.2 is out!

**Comment by nick-zh** [comment]
Hey @renatomefi ah yeah sry, i see now
Seems 7.3 builds are failing :cry:

**Comment by arnaud-lb** [comment]
Thanks @renatomefi. PHP 7.3 added some asm for string comparison that intentionally reads uninitialized memory (see https://bugs.php.net/bug.php?id=76445), causing valgrind to report some issues. I'm adding 7.3 in https://github.com/arnaud-lb/php-rdkafka/pull/249.

**Pull request closed without merging**
