### PR TITLE
Implement new KafkaConsumer

### PR DESCRIPTION
**Pull request by arnaud-lb**
This adds support for the new KafkaConsumer

Interface looks like librdkafka's: https://github.com/edenhill/librdkafka/blob/master/src-cpp/rdkafkacpp.h#L1107

Doc: `php --rc RdKafka\KafkaConsumer`

Example:

``` php
$conf = new RdKafka\Conf();
$conf->set("metadata.broker.list", "127.0.0.1:9092");
$conf->set("group.id", "test");

$consumer = new RdKafka\KafkaConsumer($conf);
$consumer->subscribe(["test"]);

while (true) {
    $message = $consumer->consume(100e3);
    switch ($message->err) {
    case RD_KAFKA_RESP_ERR_NO_ERROR:
        var_dump($message);
        break;
    case RD_KAFKA_RESP_ERR__PARTITION_EOF:
        break;
    default:
        var_dump($message->errstr());
        return;
    }
}
```

### CODE REVIEW

**Comment by doubleycn** [comment]
I have a error for make:

/home/yangyu/soft/php-rdkafka-h/conf.c: 在函数‘kafka_conf_error_cb’中:
/home/yangyu/soft/php-rdkafka-h/conf.c:134: 错误：单目‘&’的操作数必须是左值
/home/yangyu/soft/php-rdkafka-h/conf.c: 在函数‘kafka_conf_rebalance_cb’中:
/home/yangyu/soft/php-rdkafka-h/conf.c:179: 错误：单目‘&’的操作数必须是左值

`
kafka_conf_callbacks _cbs = (kafka_conf_callbacks_) opaque;
    zval _retval;
    zval *_args[3];
    zval *zrk;
    zval *zerr;
    zval *zreason;
    TSRMLS_FETCH();

```
if (!opaque) {
    return;
}

if (!cbs->error.fci.function_name) {
    return;
}

ALLOC_INIT_ZVAL(zrk);
ZVAL_ZVAL(zrk, &cbs->rk, 1, 0);
```

`
PHP 5.5.9 (cli) (built: Dec  2 2014 20:19:47) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**Comment by arnaud-lb** [comment]
@doubleycn: I believe your issue is fixed now, could you retry ?

**Comment by doubleycn** [comment]
@arnaud-lb thank you.the issue is fixed!

**Comment by scaryken** [comment]
How can I consume the messages that already exist while the "auto.offset.reset" property is in the "Topic configuration properties" and default to be "largest"? 
I don't know how to change this property to "earliest" because there seems to be only access to "Global configuration properties" in the class RdKafka\Conf.

**Comment by arnaud-lb** [comment]
@scaryken there is a `default_topic_conf` property in https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md. Support for this needs to be added to php-rdkafka.

**Comment by scaryken** [comment]
@arnaud-lb Thank you for answering my question.
 In fact I want to use the class "KafkaConsumer" for the group feature, but I cannot consume from the beginning because of that default configure. Is there a way to do this?

**Comment by arnaud-lb** [comment]
@scaryken: added RdKafka\Conf::setDefaultTopicConf(): https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka-conf.setdefaulttopicconf.html

**Pull request merged**
