### PR TITLE
Correct invalid method parameters declaration

### LINKED ISSUE #129: RdKafka\TopicConf::set method php doc issue
* PHP version: 7.0.15
 * librdkafka version: 0.9.2
 * php-rdkfaka version: 0.9.2

There's a mistake in the phpdoc of RdKafka\TopicConf::set method. It says that set gets void while it takes two argumens: name (string) and value (string): https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka-topicconf.set.html

### PR DESCRIPTION
**Pull request by Steveb-p**
Fixes #129

### CODE REVIEW

**Comment by arnaud-lb** [comment]
Thanks ! The documentation is maintained in https://github.com/arnaud-lb/php-rdkafka-doc, could you make a PR there ?

**Comment by Steveb-p** [comment]
@arnaud-lb actually it seems that https://github.com/arnaud-lb/php-rdkafka-doc/blob/master/en/reference/rdkafka/rdkafka/topicconf/set.xml already contains proper parameters. Looks like it's just the documentation is running on outdated build (https://arnaud-lb.github.io/php-rdkafka/phpdoc/rdkafka-topicconf.set.html).

**Comment by nick-zh** [comment]
@Steveb-p @arnaud-lb params were missing, opened a PR https://github.com/arnaud-lb/php-rdkafka-doc/pull/12

**Comment by Steveb-p** [comment]
Thanks @nick-zh, apparently I'm blind. I was sure those parameters were there :confused:

**Pull request closed without merging**
