### PR TITLE
Add PHP 8.1 RC6 to CI

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by ruudk** [comment]
@nick-zh Shall we merge this to prepare for PHP 8.1?

**Comment by arnaud-lb** [comment]
Thanks @ruudk 

Could you rebase on 5.x ? I've tried doing it but the build does not pass: https://github.com/arnaud-lb/php-rdkafka/runs/4209963535?check_suite_focus=true

**Comment by ruudk** [comment]
@arnaud-lb Done, please approve the workflow (you can disable this btw)

**Comment by arnaud-lb** [comment]
Thanks @ruudk 

I've disabled the approval requirement

The build is failing, I think it's because there is no `[[` in `sh`

**Comment by ruudk** [comment]
@arnaud-lb Seems to be working now 🎉  Only 1 test failure, not sure how to solve that.

**Comment by arnaud-lb** [comment]
Thanks!

I will fix the test separately

**Comment by arnaud-lb** [comment]
Unfortunately the error shows that some changes will be necessary around arginfos to support PHP 8.1. I've created an issue, help welcome :) https://github.com/arnaud-lb/php-rdkafka/issues/479

**Pull request merged**
